version: "3.8"
services:
  mongodb_inventario:
    extends:
      file: inventario/docker-compose.yml
      service: mongodb_inventario

  inventario:
    extends:
      file: inventario/docker-compose.yml
      service: inventario
    depends_on:
      - mongodb_inventario

  front-provesi:
    build: ./front-provesi
    ports:
      - "80:80"
    depends_on:
      - inventario

volumes:
  mongo-data: {}
