services:

  mongodb_inventario:
    image: mongo:latest
    container_name: mongodb_inventario
    command: mongod --port 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db/inventario

  inventario:
    build: .
    container_name: inventario
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: "fastapi dev main.py --host 0.0.0.0 --port 8000"
    depends_on:
      - mongodb_inventario

volumes:
  mongo-data:


